/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'payload-users': PayloadUserAuthOperations;
  };
  blocks: {};
  collections: {
    'payload-users': PayloadUser;
    'payload-users-sessions': PayloadUsersSession;
    'payload-users-accounts': PayloadUsersAccount;
    'payload-verifications': PayloadVerification;
    'admin-invitations': AdminInvitation;
    'payload-media': PayloadMedia;
    'payload-projects': PayloadProject;
    'payload-tickets': PayloadTicket;
    'payload-time-logs': PayloadTimeLog;
    'payload-notifications': PayloadNotification;
    'payload-companies': PayloadCompany;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'payload-users': PayloadUsersSelect<false> | PayloadUsersSelect<true>;
    'payload-users-sessions': PayloadUsersSessionsSelect<false> | PayloadUsersSessionsSelect<true>;
    'payload-users-accounts': PayloadUsersAccountsSelect<false> | PayloadUsersAccountsSelect<true>;
    'payload-verifications': PayloadVerificationsSelect<false> | PayloadVerificationsSelect<true>;
    'admin-invitations': AdminInvitationsSelect<false> | AdminInvitationsSelect<true>;
    'payload-media': PayloadMediaSelect<false> | PayloadMediaSelect<true>;
    'payload-projects': PayloadProjectsSelect<false> | PayloadProjectsSelect<true>;
    'payload-tickets': PayloadTicketsSelect<false> | PayloadTicketsSelect<true>;
    'payload-time-logs': PayloadTimeLogsSelect<false> | PayloadTimeLogsSelect<true>;
    'payload-notifications': PayloadNotificationsSelect<false> | PayloadNotificationsSelect<true>;
    'payload-companies': PayloadCompaniesSelect<false> | PayloadCompaniesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: PayloadUser & {
    collection: 'payload-users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface PayloadUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-users".
 */
export interface PayloadUser {
  id: string;
  /**
   * Company this user belongs to
   */
  company?: (string | null) | PayloadCompany;
  /**
   * Rate in USD per hour
   */
  hourlyRate: number;
  /**
   * Users chosen display name
   */
  name: string;
  /**
   * The email of the user
   */
  email: string;
  /**
   * Whether the email of the user has been verified
   */
  emailVerified: boolean;
  /**
   * The image of the user
   */
  image?: string | null;
  createdAt: string;
  updatedAt: string;
  /**
   * The role of the user
   */
  role?: string | null;
  /**
   * Whether the user is banned from the platform
   */
  banned?: boolean | null;
  /**
   * The reason for the ban
   */
  banReason?: string | null;
  /**
   * The date and time when the ban will expire
   */
  banExpires?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-companies".
 */
export interface PayloadCompany {
  id: string;
  name: string;
  /**
   * Users that belong to this company
   */
  members?: (string | PayloadUser)[] | null;
  /**
   * Stripe Customer ID used for billing
   */
  stripeCustomerId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sessions are active sessions for users. They are used to authenticate users with a session token
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-users-sessions".
 */
export interface PayloadUsersSession {
  id: string;
  /**
   * The date and time when the session will expire
   */
  expiresAt: string;
  /**
   * The unique session token
   */
  token: string;
  createdAt: string;
  updatedAt: string;
  /**
   * The IP address of the device
   */
  ipAddress?: string | null;
  /**
   * The user agent information of the device
   */
  userAgent?: string | null;
  /**
   * The user that the session belongs to
   */
  user: string | PayloadUser;
  /**
   * The admin who is impersonating this session
   */
  impersonatedBy?: string | null;
}
/**
 * Accounts are used to store user accounts for authentication providers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-users-accounts".
 */
export interface PayloadUsersAccount {
  id: string;
  /**
   * The id of the account as provided by the SSO or equal to userId for credential accounts
   */
  accountId: string;
  /**
   * The id of the provider as provided by the SSO
   */
  providerId: string;
  /**
   * The user that the account belongs to
   */
  user: string | PayloadUser;
  /**
   * The access token of the account. Returned by the provider
   */
  accessToken?: string | null;
  /**
   * The refresh token of the account. Returned by the provider
   */
  refreshToken?: string | null;
  /**
   * The id token for the account. Returned by the provider
   */
  idToken?: string | null;
  /**
   * The date and time when the access token will expire
   */
  accessTokenExpiresAt?: string | null;
  /**
   * The date and time when the refresh token will expire
   */
  refreshTokenExpiresAt?: string | null;
  /**
   * The scope of the account. Returned by the provider
   */
  scope?: string | null;
  /**
   * The hashed password of the account. Mainly used for email and password authentication
   */
  password?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * Verifications are used to verify authentication requests
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-verifications".
 */
export interface PayloadVerification {
  id: string;
  /**
   * The identifier of the verification request
   */
  identifier: string;
  /**
   * The value to be verified
   */
  value: string;
  /**
   * The date and time when the verification request will expire
   */
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-invitations".
 */
export interface AdminInvitation {
  id: string;
  role: 'admin' | 'user';
  token: string;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-media".
 */
export interface PayloadMedia {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-projects".
 */
export interface PayloadProject {
  id: string;
  name: string;
  description?: string | null;
  status: 'active' | 'paused' | 'completed' | 'archived';
  clientId: (string | PayloadUser)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-tickets".
 */
export interface PayloadTicket {
  id: string;
  ticketNumber: string;
  title: string;
  description: string;
  project: string | PayloadProject;
  client: string | PayloadUser;
  status:
    | 'to_estimate'
    | 'needs_client_review'
    | 'ready_to_develop'
    | 'development_in_progress'
    | 'ready_to_test'
    | 'done'
    | 'paid_closed'
    | 'cancelled';
  priority: 'low' | 'medium' | 'high' | 'absolute';
  /**
   * Estimated hours to complete
   */
  estimatedHours: number;
  /**
   * Hours allocated for design work
   */
  designHours?: number | null;
  /**
   * Hours allocated for PM & scoping
   */
  pmScopingHours?: number | null;
  /**
   * Hours allocated for development
   */
  devHours?: number | null;
  /**
   * Hours allocated for testing
   */
  testingHours?: number | null;
  /**
   * Hours allocated for deployment
   */
  deploymentHours?: number | null;
  /**
   * Additional precision notes visible to client
   */
  additionalPrecision?: string | null;
  /**
   * Internal notes (agency-only)
   */
  internalNotes?: string | null;
  /**
   * Total hours logged (auto-calculated)
   */
  actualHours?: number | null;
  /**
   * Require client approval before invoicing
   */
  requiresClientApproval?: boolean | null;
  /**
   * Auto-approve if client does not respond by this date
   */
  approvalDeadline?: string | null;
  /**
   * Hours to wait before auto-approval
   */
  autoApprovalHours?: number | null;
  createdBy: string | PayloadUser;
  assignedTo?: (string | PayloadUser)[] | null;
  isRevision?: boolean | null;
  /**
   * Number of revisions requested
   */
  revisionCount?: number | null;
  /**
   * Maximum allowed revisions before extra charges
   */
  maxRevisions?: number | null;
  /**
   * Parent ticket for revisions
   */
  parentTicket?: (string | null) | PayloadTicket;
  testingStartDate?: string | null;
  testingDeadline?: string | null;
  autoApprovalDate?: string | null;
  attachments?: (string | PayloadMedia)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-time-logs".
 */
export interface PayloadTimeLog {
  id: string;
  ticket: string | PayloadTicket;
  user: string | PayloadUser;
  description: string;
  date: string;
  /**
   * When work started
   */
  startTime?: string | null;
  /**
   * When work ended
   */
  endTime?: string | null;
  /**
   * Hours worked (minimum 0.25, rounds to nearest 0.25)
   */
  hours: number;
  isBillable: boolean;
  /**
   * Rate at time of logging (from client)
   */
  hourlyRate: number;
  /**
   * Calculated: hours × hourlyRate
   */
  totalAmount: number;
  invoice?: (string | null) | PayloadCompany;
  isInvoiced?: boolean | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Additional time log metadata
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-notifications".
 */
export interface PayloadNotification {
  id: string;
  recipient: string | PayloadUser;
  /**
   * Related project if applicable
   */
  project?: (string | null) | PayloadProject;
  type:
    | 'ticket_created'
    | 'estimate_ready'
    | 'ticket_approved'
    | 'testing_ready'
    | 'auto_approval_warning'
    | 'revision_requested'
    | 'payment_marked';
  title: string;
  message: string;
  isRead?: boolean | null;
  /**
   * Related ticket if applicable
   */
  relatedTicket?: (string | null) | PayloadTicket;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'payload-users';
        value: string | PayloadUser;
      } | null)
    | ({
        relationTo: 'payload-users-sessions';
        value: string | PayloadUsersSession;
      } | null)
    | ({
        relationTo: 'payload-users-accounts';
        value: string | PayloadUsersAccount;
      } | null)
    | ({
        relationTo: 'payload-verifications';
        value: string | PayloadVerification;
      } | null)
    | ({
        relationTo: 'admin-invitations';
        value: string | AdminInvitation;
      } | null)
    | ({
        relationTo: 'payload-media';
        value: string | PayloadMedia;
      } | null)
    | ({
        relationTo: 'payload-projects';
        value: string | PayloadProject;
      } | null)
    | ({
        relationTo: 'payload-tickets';
        value: string | PayloadTicket;
      } | null)
    | ({
        relationTo: 'payload-time-logs';
        value: string | PayloadTimeLog;
      } | null)
    | ({
        relationTo: 'payload-notifications';
        value: string | PayloadNotification;
      } | null)
    | ({
        relationTo: 'payload-companies';
        value: string | PayloadCompany;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'payload-users';
    value: string | PayloadUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'payload-users';
    value: string | PayloadUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-users_select".
 */
export interface PayloadUsersSelect<T extends boolean = true> {
  company?: T;
  hourlyRate?: T;
  name?: T;
  email?: T;
  emailVerified?: T;
  image?: T;
  createdAt?: T;
  updatedAt?: T;
  role?: T;
  banned?: T;
  banReason?: T;
  banExpires?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-users-sessions_select".
 */
export interface PayloadUsersSessionsSelect<T extends boolean = true> {
  expiresAt?: T;
  token?: T;
  createdAt?: T;
  updatedAt?: T;
  ipAddress?: T;
  userAgent?: T;
  user?: T;
  impersonatedBy?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-users-accounts_select".
 */
export interface PayloadUsersAccountsSelect<T extends boolean = true> {
  accountId?: T;
  providerId?: T;
  user?: T;
  accessToken?: T;
  refreshToken?: T;
  idToken?: T;
  accessTokenExpiresAt?: T;
  refreshTokenExpiresAt?: T;
  scope?: T;
  password?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-verifications_select".
 */
export interface PayloadVerificationsSelect<T extends boolean = true> {
  identifier?: T;
  value?: T;
  expiresAt?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-invitations_select".
 */
export interface AdminInvitationsSelect<T extends boolean = true> {
  role?: T;
  token?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-media_select".
 */
export interface PayloadMediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-projects_select".
 */
export interface PayloadProjectsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  status?: T;
  clientId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-tickets_select".
 */
export interface PayloadTicketsSelect<T extends boolean = true> {
  ticketNumber?: T;
  title?: T;
  description?: T;
  project?: T;
  client?: T;
  status?: T;
  priority?: T;
  estimatedHours?: T;
  designHours?: T;
  pmScopingHours?: T;
  devHours?: T;
  testingHours?: T;
  deploymentHours?: T;
  additionalPrecision?: T;
  internalNotes?: T;
  actualHours?: T;
  requiresClientApproval?: T;
  approvalDeadline?: T;
  autoApprovalHours?: T;
  createdBy?: T;
  assignedTo?: T;
  isRevision?: T;
  revisionCount?: T;
  maxRevisions?: T;
  parentTicket?: T;
  testingStartDate?: T;
  testingDeadline?: T;
  autoApprovalDate?: T;
  attachments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-time-logs_select".
 */
export interface PayloadTimeLogsSelect<T extends boolean = true> {
  ticket?: T;
  user?: T;
  description?: T;
  date?: T;
  startTime?: T;
  endTime?: T;
  hours?: T;
  isBillable?: T;
  hourlyRate?: T;
  totalAmount?: T;
  invoice?: T;
  isInvoiced?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-notifications_select".
 */
export interface PayloadNotificationsSelect<T extends boolean = true> {
  recipient?: T;
  project?: T;
  type?: T;
  title?: T;
  message?: T;
  isRead?: T;
  relatedTicket?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-companies_select".
 */
export interface PayloadCompaniesSelect<T extends boolean = true> {
  name?: T;
  members?: T;
  stripeCustomerId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}